nombre = input("¿Cuál es tu nombre? ")
apellido = input("¿Cuál es tu apellido? ")
edad = input("¿Cuál es tu edad? ")
edad = int(edad)
sueldo = input("Ingrese el sueldo: ")
sueldo = int(sueldo)
aumento = input("Ingrese el porcentaje de aumento: ")
aumento = float(aumento)/100
newSueldo = sueldo + (sueldo * aumento)
print("Hola " + nombre + " " + apellido + ", tu sueldo es: " + str(sueldo) + ", el aumento es de: " + str(aumento*100) + "% , y tu nuevo sueldo es: " + str(newSueldo)	)